development:
  adapter: postgresql
  encoding: utf8
  database: vending_machine_dev
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: vending_machine_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: vending_machine_prod
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
